# Generated by Django 6.0.1 on 2026-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('record', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('START', '대기'), ('FINISH', '완주'), ('DNF', '중도포기'), ('DSQ', '실격')], default='START', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
