# Generated by Django 6.0.1 on 2026-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='status',
            field=models.CharField(choices=[('START', '대기'), ('FINISH', '완주'), ('DNS', '미출발'), ('DNF', '중도포기'), ('DSQ', '실격')], default='START', max_length=10),
        ),
    ]
