# Generated by Django 6.0.1 on 2026-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_alter_racer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
